#!/usr/bin/env node

const steps = require('./steps');

require('./command');

(async() => {
    try {
        //Process the scores from the registry
        console.debug('Processing scores');
        await steps.processScores();
    }
    catch(e) {
        console.error(e);
    }

    console.debug('Complete');
})();