#!/usr/bin/env node

const steps = require('./steps');

require('./command');

(async() => {
    try {
        //Report on all the scores
        console.debug('Producing report');
        const scores = await steps.buildReport();

        //Write report to file
        console.debug(`Writing report to ${config.reportPath}`);
        await steps.writeReport(scores);
    }
    catch(e) {
        console.error(e);
    }

    console.debug('Complete');
})();